# Generated by Django 5.0.1 on 2025-06-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_registration_is_admin_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$miblZ0hKK4z0UK14mVIUH4$5Rc7qvY2kWjN4uKL94091oG3tGNjf7DQBB7r9+1b4rE=', max_length=128),
        ),
    ]
