# Generated by Django 5.0.1 on 2025-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$0DWXbN9LlmLuv11wC1riq1$YZNK3+DmXal+x+OwGMEhrISrSdnQVyJApp1zyogNdb0=', max_length=128),
        ),
    ]
