# Generated by Django 5.2.3 on 2025-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$a5wUaK51fCuaN18LvvEZ6f$YsPwZoiE5Mn+Hkbm1KQqSr6irfd999b7o4zBM8VnLCI=', max_length=128),
        ),
    ]
