# Generated by Django 5.2.3 on 2025-06-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$vFDMHSgVbR8pLFkzkDpY3a$NM55cknm46P6/oY+CHdnJ+jNBQNwB7ObuJu0yNB1W4g=', max_length=128),
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_login', models.CharField(max_length=100)),
                ('mt5_password', models.CharField(max_length=128)),
                ('mt5_server', models.CharField(max_length=100)),
                ('broker_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='first_app.registration')),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'ordering': ['-created_at'],
            },
        ),
    ]
