# Generated by Django 5.2.3 on 2025-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_registration_password_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$nikB4tSBCbZLS767MsQ1mO$mxyReOedto0wZY+TX2CjkcL8LNHJScQ3YEl4QfxfWaM=', max_length=128),
        ),
    ]
