# Generated by Django 5.2.3 on 2025-06-27 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$cp1pxUCCF18actEzVcEeJz$quXkV5k9xr2NjhOW8v4+xZuJ0tdQKeO/9Y/S88jESCc=', max_length=128),
        ),
        migrations.CreateModel(
            name='PNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField()),
                ('entry_time', models.DateTimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('exit_time', models.DateTimeField()),
                ('exit_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('pl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cpl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnls', to='first_app.registration')),
            ],
            options={
                'verbose_name': 'PNL',
                'verbose_name_plural': 'PNLs',
                'ordering': ['-created_at'],
            },
        ),
    ]
