# Generated by Django 5.2.3 on 2025-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_alter_registration_password_pnl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnl',
            name='trade_id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$95dq2SHaNg3DNPt33lS9ar$XUviMthxIi0B+PpSLOVKOdbgWzou0T5242XjRaxxyBc=', max_length=128),
        ),
    ]
