# Generated by Django 5.2.3 on 2025-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_alter_registration_password_plan_delete_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Lwh5mueH8P1jaIBWoC06MA$lImdhb5FNH2c11hzKl00k2mSsyg/wswMdIt+AylzFgw=', max_length=128),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
