# Generated by Django 5.2.3 on 2025-06-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_alter_registration_password_delete_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$P1ROfdSReWbH2576JRXQWs$lEGuaFEysqr4wFnUk2bMhLRJCS9nMg7X1nDbFg/pfpo=', max_length=128),
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('exit_time', models.DateTimeField()),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pl', models.DecimalField(decimal_places=4, max_digits=16)),
                ('cpl', models.DecimalField(decimal_places=4, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_histories', to='first_app.registration')),
            ],
            options={
                'verbose_name': 'Trade History',
                'verbose_name_plural': 'Trade Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
