# Generated by Django 5.2.3 on 2025-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_alter_registration_password_tradehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='forgingkey',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$m3yNGtvIUMPgdZOsQAV0Uy$rbgoMUA18EwAKkMdLJTwIyoAqvQ/oA0gg61CBOaJucg=', max_length=128),
        ),
    ]
